### ISSUE TITLE
Align header image with title

### ISSUE THREAD

**Issue by abbynormaled** [mattwells19/CATCh#3]
The top of the primary image should probably align with the H1 title. 
![image](https://github.com/mattwells19/CATCh/assets/81336679/deaaeeeb-fe39-4e11-89e1-d6382ffd5c27)

**Comment by abbynormaled** [comment]
Do you want me to see if I can adjust in Astro? I need a bit of practice at using the framework.

**Comment by mattwells19** [comment]
Hmm, the design (pictured below) doesn't have the two top-aligned. I'm open to it though if you think that'd look better!
![image](https://github.com/mattwells19/CATCh/assets/36650048/ca8b09ef-b5b4-4a6a-9172-670d91f19d16)

> Do you want me to see if I can adjust in Astro? I need a bit of practice at using the framework.

Absolutely! Let me merge the two PR's so that you can branch off of `main`.

**Comment by mattwells19** [comment]
> Hmm, the design (pictured below) doesn't have the two top-aligned. I'm open to it though if you think that'd look better! > 
> > Do you want me to see if I can adjust in Astro? I need a bit of practice at using the framework.
> 
> Absolutely! Let me merge the two PR's so that you can branch off of `main`.

Or if you want to just push to `mvp/home/upcoming_shows_section` directly that works as well!

**Comment by abbynormaled** [comment]
Well, I think there's maybe more padding above that row? It just feels too close to the top nav 
> Hmm, the design (pictured below) doesn't have the two top-aligned. I'm open to it though if you think that'd look better! >

**Comment by mattwells19** [comment]
> Well, I think there's maybe more padding above that row? It just feels too close to the top nav

I added some extra padding to that top portion in the PR. Let me know what ya think!

**Comment by mattwells19** [comment]
@abbynormaled I'm going to go ahead and merge the PRs so that we can keep rolling. Happy to iterate on this more as we go!
